name: Build

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:


jobs:  
  build:
    runs-on: ubuntu-latest


    steps:
        - name: Checkout repository
          uses: actions/checkout@v5
        - name: Set up JDK 21
          uses: actions/setup-java@v5
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '21'
            cache: 'maven'
        - name: Build with Maven
          run: ./mvnw -B package
  integration-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - run: echo "Run integration tests"

  build-images:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - run: echo "Build docker images"

  deploy:
    runs-on: ubuntu-latest
    needs: build-images
    steps:        
    - run: echo "Deploy to production"  
    
